- id: semistandard
  name: Run `semistandard` on javascript files
  entry: semistandard
  language: node
  files: \.(js|jsx)$
  args: []
  additional_dependencies: ['semistandard@11.0.0']
  minimum_pre_commit_version: 0.7.0
- id: tslint
  name: Run `tslint` on typescript files
  entry: tslint
  language: node
  files: \.ts$
  args: []
  additional_dependencies: ['typescript@2.3.4', 'tslint@5.4.3']

